// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `CineTicketService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <CineTicketService.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __UC3M__CineTicketService__consulta_name = "consulta";

const ::std::string __UC3M__CineTicketService__reserva_name = "reserva";

const ::std::string __UC3M__CineTicketService__cancela_name = "cancela";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::UC3M::upCast(::IceProxy::UC3M::CineTicketService* p) { return p; }

void
::IceProxy::UC3M::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::UC3M::CineTicketService>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::UC3M::CineTicketService;
        v->__copyFrom(proxy);
    }
}

::UC3M::consultasesion
IceProxy::UC3M::CineTicketService::consulta(::Ice::Int horaSesion, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __UC3M__CineTicketService__consulta_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__UC3M__CineTicketService__consulta_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::UC3M::CineTicketService* __del = dynamic_cast< ::IceDelegate::UC3M::CineTicketService*>(__delBase.get());
            return __del->consulta(horaSesion, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::UC3M::CineTicketService::begin_consulta(::Ice::Int horaSesion, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__UC3M__CineTicketService__consulta_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __UC3M__CineTicketService__consulta_name, __del, __cookie);
    try
    {
        __result->__prepare(__UC3M__CineTicketService__consulta_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(horaSesion);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::UC3M::consultasesion
IceProxy::UC3M::CineTicketService::end_consulta(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __UC3M__CineTicketService__consulta_name);
    ::UC3M::consultasesion __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::Ice::Int
IceProxy::UC3M::CineTicketService::reserva(::Ice::Int horaSesion, ::Ice::Int numeroButaca, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __UC3M__CineTicketService__reserva_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__UC3M__CineTicketService__reserva_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::UC3M::CineTicketService* __del = dynamic_cast< ::IceDelegate::UC3M::CineTicketService*>(__delBase.get());
            return __del->reserva(horaSesion, numeroButaca, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::UC3M::CineTicketService::begin_reserva(::Ice::Int horaSesion, ::Ice::Int numeroButaca, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__UC3M__CineTicketService__reserva_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __UC3M__CineTicketService__reserva_name, __del, __cookie);
    try
    {
        __result->__prepare(__UC3M__CineTicketService__reserva_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(horaSesion);
        __os->write(numeroButaca);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::UC3M::CineTicketService::end_reserva(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __UC3M__CineTicketService__reserva_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::Ice::Int
IceProxy::UC3M::CineTicketService::cancela(::Ice::Int horaSesion, ::Ice::Int numeroButaca, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __UC3M__CineTicketService__cancela_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__UC3M__CineTicketService__cancela_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::UC3M::CineTicketService* __del = dynamic_cast< ::IceDelegate::UC3M::CineTicketService*>(__delBase.get());
            return __del->cancela(horaSesion, numeroButaca, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::UC3M::CineTicketService::begin_cancela(::Ice::Int horaSesion, ::Ice::Int numeroButaca, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__UC3M__CineTicketService__cancela_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __UC3M__CineTicketService__cancela_name, __del, __cookie);
    try
    {
        __result->__prepare(__UC3M__CineTicketService__cancela_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(horaSesion);
        __os->write(numeroButaca);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::UC3M::CineTicketService::end_cancela(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __UC3M__CineTicketService__cancela_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::UC3M::CineTicketService::ice_staticId()
{
    return ::UC3M::CineTicketService::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::UC3M::CineTicketService::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::UC3M::CineTicketService);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::UC3M::CineTicketService::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::UC3M::CineTicketService);
}

::IceProxy::Ice::Object*
IceProxy::UC3M::CineTicketService::__newInstance() const
{
    return new CineTicketService;
}

::UC3M::consultasesion
IceDelegateM::UC3M::CineTicketService::consulta(::Ice::Int horaSesion, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __UC3M__CineTicketService__consulta_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(horaSesion);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::UC3M::consultasesion __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::UC3M::CineTicketService::reserva(::Ice::Int horaSesion, ::Ice::Int numeroButaca, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __UC3M__CineTicketService__reserva_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(horaSesion);
        __os->write(numeroButaca);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::UC3M::CineTicketService::cancela(::Ice::Int horaSesion, ::Ice::Int numeroButaca, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __UC3M__CineTicketService__cancela_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(horaSesion);
        __os->write(numeroButaca);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::UC3M::consultasesion
IceDelegateD::UC3M::CineTicketService::consulta(::Ice::Int horaSesion, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::UC3M::consultasesion& __result, ::Ice::Int __p_horaSesion, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_horaSesion(__p_horaSesion)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::UC3M::CineTicketService* servant = dynamic_cast< ::UC3M::CineTicketService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->consulta(_m_horaSesion, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::UC3M::consultasesion& _result;
        ::Ice::Int _m_horaSesion;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __UC3M__CineTicketService__consulta_name, ::Ice::Normal, __context);
    ::UC3M::consultasesion __result;
    try
    {
        _DirectI __direct(__result, horaSesion, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Int
IceDelegateD::UC3M::CineTicketService::reserva(::Ice::Int horaSesion, ::Ice::Int numeroButaca, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, ::Ice::Int __p_horaSesion, ::Ice::Int __p_numeroButaca, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_horaSesion(__p_horaSesion),
            _m_numeroButaca(__p_numeroButaca)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::UC3M::CineTicketService* servant = dynamic_cast< ::UC3M::CineTicketService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->reserva(_m_horaSesion, _m_numeroButaca, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int& _result;
        ::Ice::Int _m_horaSesion;
        ::Ice::Int _m_numeroButaca;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __UC3M__CineTicketService__reserva_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, horaSesion, numeroButaca, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Int
IceDelegateD::UC3M::CineTicketService::cancela(::Ice::Int horaSesion, ::Ice::Int numeroButaca, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, ::Ice::Int __p_horaSesion, ::Ice::Int __p_numeroButaca, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_horaSesion(__p_horaSesion),
            _m_numeroButaca(__p_numeroButaca)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::UC3M::CineTicketService* servant = dynamic_cast< ::UC3M::CineTicketService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->cancela(_m_horaSesion, _m_numeroButaca, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int& _result;
        ::Ice::Int _m_horaSesion;
        ::Ice::Int _m_numeroButaca;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __UC3M__CineTicketService__cancela_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, horaSesion, numeroButaca, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* UC3M::upCast(::UC3M::CineTicketService* p) { return p; }

namespace
{
const ::std::string __UC3M__CineTicketService_ids[2] =
{
    "::Ice::Object",
    "::UC3M::CineTicketService"
};

}

bool
UC3M::CineTicketService::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__UC3M__CineTicketService_ids, __UC3M__CineTicketService_ids + 2, _s);
}

::std::vector< ::std::string>
UC3M::CineTicketService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__UC3M__CineTicketService_ids[0], &__UC3M__CineTicketService_ids[2]);
}

const ::std::string&
UC3M::CineTicketService::ice_id(const ::Ice::Current&) const
{
    return __UC3M__CineTicketService_ids[1];
}

const ::std::string&
UC3M::CineTicketService::ice_staticId()
{
    return __UC3M__CineTicketService_ids[1];
}

::Ice::DispatchStatus
UC3M::CineTicketService::___consulta(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int horaSesion;
    __is->read(horaSesion);
    __inS.endReadParams();
    ::UC3M::consultasesion __ret = consulta(horaSesion, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
UC3M::CineTicketService::___reserva(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int horaSesion;
    ::Ice::Int numeroButaca;
    __is->read(horaSesion);
    __is->read(numeroButaca);
    __inS.endReadParams();
    ::Ice::Int __ret = reserva(horaSesion, numeroButaca, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
UC3M::CineTicketService::___cancela(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int horaSesion;
    ::Ice::Int numeroButaca;
    __is->read(horaSesion);
    __is->read(numeroButaca);
    __inS.endReadParams();
    ::Ice::Int __ret = cancela(horaSesion, numeroButaca, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __UC3M__CineTicketService_all[] =
{
    "cancela",
    "consulta",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "reserva"
};

}

::Ice::DispatchStatus
UC3M::CineTicketService::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__UC3M__CineTicketService_all, __UC3M__CineTicketService_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __UC3M__CineTicketService_all)
    {
        case 0:
        {
            return ___cancela(in, current);
        }
        case 1:
        {
            return ___consulta(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
        case 6:
        {
            return ___reserva(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
UC3M::CineTicketService::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
UC3M::CineTicketService::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
UC3M::__patch(CineTicketServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::UC3M::CineTicketServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::UC3M::CineTicketService::ice_staticId(), v);
    }
}
